version = 1

[[annotations]]
path = [
    ".releaserc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pyproject.toml",
    "uv.lock",
    "src/oc_graphenricher/APIs/stopwords-it.txt",
    "tests/fixtures/test_merge_br.rdf",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
